#!/bin/sh
DEVICE_NAME=`cat /proc/sys/kernel/hostname`;
MACFILE="/etc/known_mac";

CHAT_ID="101_CHANGEME_101"
BOT_ID="101_CHANGEME_101"

MESSAGE="New device found! Router name: DEVICE_NAME, MAC: MAC_ADDR; IP: IP_ADDR; Hostname: HOST_NAME"

TPL_PAYLOAD="{\"chat_id\": \"$CHAT_ID\", \"text\": \"_MESSAGE_\"}"
REQUEST_URI="https://api.telegram.org/bot$BOT_ID/sendMessage"

while true; do
        MACS=`cat /var/lib/misc/dnsmasq.leases | sed "s/\*/NO_NAME/g" | sed "s/$/@#@#@#@#/g"`;
        echo $MACS | sed "s/@#@#@#@# /\r\n/g" | cut -d" " -f2 | 
        while read i; 
            do grep "$i" -i "$MACFILE" > /dev/null 2>&1; 
                if [ $? -eq 0 ]; 
                    then 
                        echo "$i is known"; 
                    else
                        IP=`echo $MACS | sed "s/@#@#@#@# /\r\n/g" | grep "$i"  | cut -d" " -f3`;
                        HOSTNAME=`echo $MACS | sed "s/@#@#@#@# /\r\n/g" | grep "$i" | cut -d" " -f4`;
                        echo "$i $IP $HOSTNAME" >> "$MACFILE";
                        CURRENT_MESSAGE=`echo $MESSAGE | sed "s/DEVICE_NAME/$DEVICE_NAME/g" | sed "s/MAC_ADDR/$i/g" | sed "s/IP_ADDR/$IP/g" | sed "s/HOST_NAME/$HOSTNAME/g"`;
                        PAYLOAD=`echo -n $TPL_PAYLOAD | sed "s/_MESSAGE_/$CURRENT_MESSAGE/g"`; 
                        echo "Mac $i is not known! Addind to known list and sending push notification. IP: $IP; HOSTNAME: $HOSTNAME";
                        curl -X POST -H 'Content-Type: application/json' -d "$PAYLOAD" "$REQUEST_URI" >/dev/null 2>&1;
                fi;
            done;
    sleep 60;
done;
 